// Refresh per-book Amazon rating + review count into src/data/ratings.ts.
//
// Google can show review stars for a Book only when the aggregateRating is
// GENUINE and VISIBLE on the page. So this pulls each book's real current
// Amazon rating (value + count), the site displays "X.X on Amazon (N ratings)"
// on the book page, and the same numbers are marked up in JSON-LD. Re-run
// monthly to keep them accurate (they drift as reviews come in).
//
// Amazon serves a bot wall to plain HTTP clients, so we drive headless Chrome.
//
//   npm run refresh-ratings            # write src/data/ratings.ts
//   npm run refresh-ratings -- --dry   # print a table, write nothing
//
// A book with no ratings yet is simply omitted (no rating shown, no markup) —
// never invent a rating.

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BOOKS = path.resolve(__dirname, '..', 'src', 'data', 'books.ts');
const OUT = path.resolve(__dirname, '..', 'src', 'data', 'ratings.ts');
const DRY = process.argv.includes('--dry');
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

/** Pull { id, asin } pairs out of books.ts in file order. */
function parseBooks(src) {
  const lines = src.split('\n');
  const books = [];
  let cur = null;
  for (const ln of lines) {
    const id = ln.match(/^ {4}id: '([^']+)',$/);
    if (id) {
      cur = { id: id[1], asin: null };
      books.push(cur);
      continue;
    }
    if (!cur) continue;
    const az = ln.match(/^ {4}amazonUrl: dp\('([^']+)'\),$/);
    if (az && !cur.asin) cur.asin = az[1];
  }
  return books;
}

async function scrapeRating(page, asin) {
  await page.goto(`https://www.amazon.com/dp/${asin}`, { waitUntil: 'domcontentloaded', timeout: 30000 });
  return page.evaluate(() => {
    let rating = null;
    const altEl =
      document.querySelector('#acrPopover .a-icon-alt') ||
      document.querySelector('i[data-hook="average-star-rating"] .a-icon-alt') ||
      document.querySelector('#averageCustomerReviews .a-icon-alt');
    if (altEl) {
      const m = altEl.textContent.match(/([\d.]+)\s+out of\s+5/);
      if (m) rating = parseFloat(m[1]);
    }
    if (rating === null) {
      const pop = document.querySelector('#acrPopover');
      const m = pop && (pop.getAttribute('title') || '').match(/([\d.]+)\s+out of\s+5/);
      if (m) rating = parseFloat(m[1]);
    }
    let count = null;
    const cntEl =
      document.querySelector('#acrCustomerReviewText') ||
      document.querySelector('[data-hook="total-review-count"]');
    if (cntEl) {
      const m = cntEl.textContent.replace(/,/g, '').match(/(\d+)/);
      if (m) count = parseInt(m[1], 10);
    }
    return { rating, count };
  });
}

const books = parseBooks(await readFile(BOOKS, 'utf8'));
console.log(`Scraping Amazon ratings for ${books.length} books${DRY ? ' (dry run)' : ''}…\n`);

const browser = await puppeteer.launch({
  args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
});

const results = [];
const failures = [];
for (const b of books) {
  if (!b.asin) {
    failures.push(`${b.id} — no ASIN`);
    continue;
  }
  const page = await browser.newPage();
  await page.setUserAgent(UA);
  try {
    const { rating, count } = await scrapeRating(page, b.asin);
    if (rating != null && count != null && count > 0) {
      results.push({ id: b.id, ratingValue: rating, reviewCount: count });
      console.log(`  ✓ ${b.id.padEnd(28)} ${rating} ★  (${count} ratings)`);
    } else {
      console.log(`  · ${b.id.padEnd(28)} no ratings yet — omitted`);
    }
  } catch (e) {
    failures.push(`${b.id} — ${e.message.split('\n')[0]}`);
    console.log(`  ✗ ${b.id.padEnd(28)} lookup failed`);
  } finally {
    await page.close();
  }
}
await browser.close();

console.log(`\n${results.length}/${books.length} books have a live Amazon rating.`);
if (failures.length) console.warn(`\n⚠️  ${failures.length} failed:\n  ` + failures.join('\n  '));

if (DRY) {
  console.log('\nDry run — src/data/ratings.ts not written.');
} else {
  const today = new Date().toISOString().slice(0, 10);
  const body = results
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((r) => `  '${r.id}': { ratingValue: ${r.ratingValue}, reviewCount: ${r.reviewCount} },`)
    .join('\n');
  const file = `// AUTO-GENERATED by scripts/refresh-ratings.mjs — do not edit by hand.
// Real Amazon rating + review count per book, scraped ${today}. Re-run monthly:
//   npm run refresh-ratings
// Books with no ratings yet are omitted (no stars shown, nothing marked up).

export interface BookRating {
  ratingValue: number;
  reviewCount: number;
}

/** When these numbers were last pulled from Amazon (ISO date). */
export const RATINGS_UPDATED = '${today}';

export const BOOK_RATINGS: Record<string, BookRating> = {
${body}
};
`;
  await writeFile(OUT, file);
  console.log(`\nWrote ${path.relative(process.cwd(), OUT)} (${results.length} ratings, dated ${today}).`);
  if (!results.length) console.log('  (no book has an Amazon rating yet — stars stay hidden until one does)');
}
