// AUTO-GENERATED by scripts/refresh-ratings.mjs — do not edit by hand.
// Real Amazon rating + review count per book, scraped 2026-08-04. Re-run monthly:
//   npm run refresh-ratings
// Books with no ratings yet are omitted (no stars shown, nothing marked up).
// As of 2026-08-04 all 18 titles have 0 Amazon ratings, so this map is empty and
// no stars/aggregateRating render anywhere — by design, never invent a rating.

export interface BookRating {
  ratingValue: number;
  reviewCount: number;
}

/** When these numbers were last pulled from Amazon (ISO date). */
export const RATINGS_UPDATED = '2026-08-04';

export const BOOK_RATINGS: Record<string, BookRating> = {
};
